### ISSUE TITLE
윤영서 코드리뷰입니다.

### ISSUE THREAD

**Issue by YeongseoYoon** [flynnpark/nomad-movie-app#1]
1. src/components/commons/index.ts 에서
```js
import styled from 'styled-components';

import { MAX_WIDTH } from '../../constants';

export const Article = styled.article` 
  max-width: ${MAX_WIDTH}px;
  margin: 0 auto;
`;
```
로 다른 컴포넌트와 달리 style.ts 만드시지 않고 index로 만드셨는데 이유가 있나요? 밖에서 쓰기 위함이라고 하면 레이아웃 컴포넌트를 만들고 거기서 스타일링을 하면 안됐을까요? 
궁금하네요 어떤게 더 권장되는 방식인지

article로 시멘틱 태그 쓰신거 좋네요 저도 그렇게 쓸걸 그랬어요

2. Header에서 item이 분리되어있는 부분이나 MovieCard로 분리하신 부분은 사실 저도 그렇게 해볼까했는데 귀찮아서 안했거든요... 반성하게 되네용

3. useTypeFromQuery 이부분 너무 좋아서 계속 봤어요 제 머리속에서 생각 못할거 같은 느낌이라ㅋㅋㅋㅋㅋ 다음에 이런 양식 필요하면 쌔비지 하겠습니다

4. 우와 이거
```js
          {[
            { key: 'Budget', value: movieDetail.budget },
            { key: 'Revenue', value: movieDetail.revenue },
            { key: 'Runtime', value: movieDetail.runtime },
            { key: 'Rating', value: movieDetail.vote_average },
            { key: 'Homepage', value: movieDetail.homepage },
          ].map(({ key, value }) => {
            return (
              value && (
                <Information key={key}>
                  <ItemName>{key}:</ItemName> {value}
                </Information>
              )
            );
          })}
```
저는 코드가 너무 지저분해진다 생각했는데, 이걸 이렇게 하면 되는거네요? 바보네,,,
왜 동적으로 불러올때만 저렇게 map을 사용한다고 생각했을까요?

5. 
```
export enum MovieListType {
  COMING_SOONG = 'coming-soon',
  NOW_PLAYING = 'now-playing',
  POPULAR = 'popular',
}

```
아잇참 오타 발견했습니다 커밍숭~

그냥 감탄만 하고 끝나네요ㅋㅋㅋㅋㅋ그래도 자꾸 리뷰해달라고 하신 덕분에 좋은 코드 잘 봤어요 감사합니다

**Comment by flynnpark** [comment]
아차차 오타 일부러 숨겨놨는데~ 정말 꼼꼼히 보시네요 역시 킹갓영서님... 바로 발견해버리시네~
1번 같은 경우는 스타일드로 하면 더 좋았겠다는 생각이 드네요 흠... 권장되는 방식이라기 보다는 일관된 방식이라고 하는 게 더 맞는 거같아유... 감사해요!
